enum EActionTypes {
  SET_NUMBER = 'SET_NUMBER',

  SET_TEXT = 'SET_TEXT',

  SET_APPS = 'SET_APPS',
  UPDATE_APP = 'UPDATE_APP',
  CREATE_APP = 'CREATE_APP',
  DELETE_APP = 'DELETE_APP',

  TRIGGER_VERIFICATION = 'TRIGGER_VERIFICATION',
  LOGIN = 'LOGIN',
  INIT_LOGOUT = 'INIT_LOGOUT',
  LOGIN_VERIFIED = 'LOGIN_VERIFIED',
  LOGOUT = 'LOGOUT',
}

export default EActionTypes;
